all: 
	javac client/*.java
	javac client/*/*.java
	javac client/*/*/*.java
	javac client/*/*/*/*.java


map:
	javac client/node/map/*.java
	javac client/node/*.java
	javac client/ArgumentParser.java
	javac client/SettingsContainer.java

clean:	
	rm -f *.class